### ISSUE TITLE
Make the path to the database to be a positional argument

### ISSUE THREAD

**Issue by dkolmakov** [dkolmakov/hm#15]
Path to the database is required by any possible command and currently is conveyed to utility with a special key:
`hm-db --db /path/to/database ...`
We can omit the key for convenience, so the call will look like:
`hm-db /path/to/database ...`

**Comment by AmirQadir** [comment]
I'll take that 
one last thing which I need to know. 
Currently, we do not have any positional argument when executing the script. So, I should set it to $1. is that correct?
