### ISSUE TITLE
Check the ways to decrease commands loading time

### ISSUE THREAD

**Issue by dkolmakov** [dkolmakov/hm#45]
When hm command is not used the temporary file can collect many commands, and it will require a significant amount of time to load them.
1. Use any job scheduler to load commands at night
2. If possible optimize loading process

**Comment by dylanjtastet** [comment]
Hi Dmitry,

I studied HM with kernel-tracing software for a class project, and I think I may have this sorted out! Sqlite is kicking off an fsync after every write, which causes it to wait on a long-running synchronous write from the journaling block device (my guess is it treats the entire fsync as an atomic transaction)? This means each write can take ~70ms!

While we wait on a fix from sqlite, you can improve performance by disabling the file system syncs. Technically this may cause the database to corrupt if there is a loss of power and some data does not make it to the disk surface, but this is unlikely given the size of the writes (and the fsync takes so long that it might corrupt your db if it is interrupted anyway). If you want to go this route, run `PRAGMA synchronous = OFF;` when you are initializing your database.

I have attached some screenshots that show the hm-db process waiting for several milliseconds and the improvement in latency when fsyncs are disabled.

Happy hacking!

-Dylan

### Fairly large latency inserting from a temporary file of only ~30 entries:
![latency_issue](https://user-images.githubusercontent.com/18294964/69507218-c7d07c00-0eff-11ea-8bba-29729def863d.PNG)
### Source of the latency: a ~70ms synchronous write from the journaler:
![journaler_write](https://user-images.githubusercontent.com/18294964/69507135-7a540f00-0eff-11ea-98c7-15f76b1b8b26.PNG)
### Without fsyncs, the entire update only takes 11ms:
![nojournal_fix](https://user-images.githubusercontent.com/18294964/69507149-8770fe00-0eff-11ea-83db-5f3cc23ed0a1.PNG)

**Comment by dkolmakov** [comment]
Hi Dylan,

Many thanks for a such great finding! 
I'm not very familiar with sqlite and now I have a questions regarding this issue - does the sqlite have  some sort of "bulk update" so the fsync will be issued not for every write but for a bunch of writes?

**Comment by dkolmakov** [comment]
Looks like I solved the issue by wrapping the insertion loop as suggested [here](https://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database):
```
BEGIN TRANSACTION;
insert()
insert()
...
insert()
COMMIT;
```
It dramatically speed-ups the loading process. Now loading of 100000 requires only 6 seconds on a system with HDD (before it took the same time to load 10 lines). You can check it in branch "insertion-speed-up".

Thank you again for the correctly formulated problem!
